export {
	answerTelegramCallbackQuery,
	answerTelegramCallbackQueryBestEffort,
	deleteTelegramMessage,
	editOrSendTelegramText,
	editTelegramMarkdownMessage,
	editTelegramTextMessage,
	sendTelegramMarkdownReply,
	sendTelegramTextReply,
	textMessageBody,
	type DeleteTelegramMessageOptions,
	type EditOrSendTextOptions,
	type SendTextReplyOptions,
	type TelegramJsonCall,
} from "./message-ops.js";
